// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEGamrqtft_7LHZ85QenzyVp8VZoC0uX8',
    appId: '1:893044182440:web:2e9a588f5ecc58825da19d',
    messagingSenderId: '893044182440',
    projectId: 'abolashin-9be77',
    authDomain: 'abolashin-9be77.firebaseapp.com',
    storageBucket: 'abolashin-9be77.firebasestorage.app',
    measurementId: 'G-1BNT33PJ0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbKRDgu6vlgbf73MSIFVk8oOO-s4UL3xg',
    appId: '1:893044182440:android:2b32b6fa21a4eb515da19d',
    messagingSenderId: '893044182440',
    projectId: 'abolashin-9be77',
    storageBucket: 'abolashin-9be77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZznIElrn99Pzl7IreijWRVOIDClSQlEI',
    appId: '1:893044182440:ios:609262e7f80623055da19d',
    messagingSenderId: '893044182440',
    projectId: 'abolashin-9be77',
    storageBucket: 'abolashin-9be77.firebasestorage.app',
    iosBundleId: 'com.abolashine.theOne.abolashin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZznIElrn99Pzl7IreijWRVOIDClSQlEI',
    appId: '1:893044182440:ios:609262e7f80623055da19d',
    messagingSenderId: '893044182440',
    projectId: 'abolashin-9be77',
    storageBucket: 'abolashin-9be77.firebasestorage.app',
    iosBundleId: 'com.abolashine.theOne.abolashin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEGamrqtft_7LHZ85QenzyVp8VZoC0uX8',
    appId: '1:893044182440:web:08a901d2bb8eca4c5da19d',
    messagingSenderId: '893044182440',
    projectId: 'abolashin-9be77',
    authDomain: 'abolashin-9be77.firebaseapp.com',
    storageBucket: 'abolashin-9be77.firebasestorage.app',
    measurementId: 'G-SN5GFHP0G4',
  );
}
